using System.Diagnostics;
using System.Globalization;
using System.Reflection;

namespace CertificateGet.Services;

/// <summary>
/// The agent manual built into the exe (docs/help and docs/help/es, generated by docs/build-docs.py), in English
/// and Spanish. Opening a volume writes all eight pages to %LOCALAPPDATA%\CertificateGet\help (Spanish in help\es) —
/// they link to each other, and to the same volume in the other language, by relative file name — and shows the
/// chosen one in the default browser.
/// </summary>
public static class HelpDocs
{
    public record Volume(string File, string Title, string Summary, string Glyph);

    public const string English = "en", Spanish = "es";

    private static readonly IReadOnlyList<Volume> VolumesEn = new[]
    {
        new Volume("getting-started.html", "Getting Started",
            "Install the agent on Windows or Linux step by step, describe where the certificate goes, and connect this app to it.", ""),
        new Volume("programmers-guide.html", "Programmer's Guide",
            "How a deployment runs, how files and backups are written, restarts and commands, security, troubleshooting.", ""),
        new Volume("template-guide.html", "Template Guide",
            "Ready-made agent.json for NetTalk, HAProxy, Cockpit and TSplus, with the reasoning behind each setting.", ""),
        new Volume("reference.html", "Reference",
            "Every agent.json field, file source, destination kind, command and HTTP endpoint.", ""),
    };

    private static readonly IReadOnlyList<Volume> VolumesEs = new[]
    {
        new Volume("getting-started.html", "Primeros pasos",
            "Instale el agente en Windows o Linux paso a paso, describa adónde va el certificado y conecte esta aplicación.", ""),
        new Volume("programmers-guide.html", "Guía del programador",
            "Cómo se ejecuta un despliegue, cómo se escriben archivos y copias, reinicios y comandos, seguridad, solución de problemas.", ""),
        new Volume("template-guide.html", "Guía de plantillas",
            "agent.json listos para NetTalk, HAProxy, Cockpit y TSplus, con el porqué de cada ajuste.", ""),
        new Volume("reference.html", "Referencia",
            "Cada campo de agent.json, origen de archivo, tipo de destino, comando y endpoint HTTP.", ""),
    };

    public static IReadOnlyList<Volume> Volumes(string lang) => lang == Spanish ? VolumesEs : VolumesEn;

    /// <summary>Spanish when Windows is set to Spanish, otherwise English.</summary>
    public static string DefaultLanguage =>
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == Spanish ? Spanish : English;

    public static string Folder => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CertificateGet", "help");

    public static void Open(string file, string lang = English)
    {
        var asm = Assembly.GetExecutingAssembly();
        // Rewritten every time, so the copy on disk always matches this version of the app.
        foreach (var (code, folder, prefix) in new[] { (English, Folder, "help."), (Spanish, Path.Combine(Folder, Spanish), "help.es.") })
        {
            Directory.CreateDirectory(folder);
            foreach (var v in Volumes(code))
            {
                using var src = asm.GetManifestResourceStream(prefix + v.File)
                                ?? throw new FileNotFoundException($"The help file {prefix + v.File} is not built into this version of the app.");
                using var dst = File.Create(Path.Combine(folder, v.File));
                src.CopyTo(dst);
            }
        }
        var target = lang == Spanish ? Path.Combine(Folder, Spanish, file) : Path.Combine(Folder, file);
        Process.Start(new ProcessStartInfo(target) { UseShellExecute = true });
    }
}
