using System.Diagnostics;
using System.Globalization;
using System.Reflection;

namespace CertificateGet.Services;

/// <summary>
/// The CertificateGet manual (the app and the agent) built into the exe (docs/help and docs/help/es, generated by docs/build-docs.py), in English
/// and Spanish. Opening a volume writes all eight pages to %LOCALAPPDATA%\CertificateGet\help (Spanish in help\es) —
/// they link to each other, and to the same volume in the other language, by relative file name — and shows the
/// chosen one in the default browser.
/// </summary>
public static class HelpDocs
{
    public record Volume(string File, string Title, string Summary, string Glyph);

    public const string English = "en", Spanish = "es";

    private static readonly IReadOnlyList<Volume> VolumesEn = new[]
    {
        new Volume("getting-started.html", "Getting Started",
            "Install the app and request your first certificate, then install the agent on Windows or Linux and connect it.", ""),
        new Volume("programmers-guide.html", "Programmer's Guide",
            "Validation methods, Let's Encrypt and ZeroSSL, renewals, SFTP and agent deployment, storage; how the agent works.", ""),
        new Volume("template-guide.html", "Template Guide",
            "Recipes for IIS, wildcards and SFTP, then ready-made agent.json for NetTalk, HAProxy, Cockpit and TSplus.", ""),
        new Volume("reference.html", "Reference",
            "Every file format and setting of the app; every agent.json field, command and HTTP endpoint.", ""),
    };

    private static readonly IReadOnlyList<Volume> VolumesEs = new[]
    {
        new Volume("getting-started.html", "Primeros pasos",
            "Instale la aplicación y solicite su primer certificado; después instale el agente en Windows o Linux y conéctelo.", ""),
        new Volume("programmers-guide.html", "Guía del programador",
            "Métodos de validación, Let's Encrypt y ZeroSSL, renovaciones, despliegue por SFTP y agente, almacén; cómo funciona el agente.", ""),
        new Volume("template-guide.html", "Guía de plantillas",
            "Recetas para IIS, comodines y SFTP, y agent.json listos para NetTalk, HAProxy, Cockpit y TSplus.", ""),
        new Volume("reference.html", "Referencia",
            "Cada formato de archivo y ajuste de la aplicación; cada campo de agent.json, comando y endpoint HTTP.", ""),
    };

    public static IReadOnlyList<Volume> Volumes(string lang) => lang == Spanish ? VolumesEs : VolumesEn;

    /// <summary>Spanish when Windows is set to Spanish, otherwise English.</summary>
    public static string DefaultLanguage =>
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName == Spanish ? Spanish : English;

    public static string Folder => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CertificateGet", "help");

    public static void Open(string file, string lang = English)
    {
        var asm = Assembly.GetExecutingAssembly();
        // Rewritten every time, so the copy on disk always matches this version of the app.
        foreach (var (code, folder, prefix) in new[] { (English, Folder, "help."), (Spanish, Path.Combine(Folder, Spanish), "help.es.") })
        {
            Directory.CreateDirectory(folder);
            foreach (var v in Volumes(code))
            {
                using var src = asm.GetManifestResourceStream(prefix + v.File)
                                ?? throw new FileNotFoundException($"The help file {prefix + v.File} is not built into this version of the app.");
                using var dst = File.Create(Path.Combine(folder, v.File));
                src.CopyTo(dst);
            }
        }
        var target = lang == Spanish ? Path.Combine(Folder, Spanish, file) : Path.Combine(Folder, file);
        Process.Start(new ProcessStartInfo(target) { UseShellExecute = true });
    }
}
