using System.Diagnostics;
using System.Reflection;

namespace CertificateGet.Services;

/// <summary>
/// The agent manual built into the exe (docs/help, generated by docs/build-docs.py). Opening a volume writes
/// all four to %LOCALAPPDATA%\CertificateGet\help — they link to each other by file name — and shows the
/// chosen one in the default browser.
/// </summary>
public static class HelpDocs
{
    public record Volume(string File, string Title, string Summary, string Glyph);

    public static readonly IReadOnlyList<Volume> Volumes = new[]
    {
        new Volume("getting-started.html", "Getting Started",
            "Install the agent on Windows or Linux step by step, describe where the certificate goes, and connect this app to it.", ""),
        new Volume("programmers-guide.html", "Programmer's Guide",
            "How a deployment runs, how files and backups are written, restarts and commands, security, troubleshooting.", ""),
        new Volume("template-guide.html", "Template Guide",
            "Ready-made agent.json for NetTalk, HAProxy, Cockpit and TSplus, with the reasoning behind each setting.", ""),
        new Volume("reference.html", "Reference",
            "Every agent.json field, file source, destination kind, command and HTTP endpoint.", ""),
    };

    public static string Folder => Path.Combine(
        Environment.GetFolderPath(Environment.SpecialFolder.LocalApplicationData), "CertificateGet", "help");

    public static void Open(string file)
    {
        var asm = Assembly.GetExecutingAssembly();
        Directory.CreateDirectory(Folder);
        // Rewritten every time, so the copy on disk always matches this version of the app.
        foreach (var v in Volumes)
        {
            using var src = asm.GetManifestResourceStream("help." + v.File)
                            ?? throw new FileNotFoundException($"The help file {v.File} is not built into this version of the app.");
            using var dst = File.Create(Path.Combine(Folder, v.File));
            src.CopyTo(dst);
        }
        Process.Start(new ProcessStartInfo(Path.Combine(Folder, file)) { UseShellExecute = true });
    }
}
